### ISSUE TITLE
z way error pimatic

### ISSUE THREAD

**Issue by DerGrafausB** [MMore/pimatic-plugin-template#31]
Hi,

can you help me, what this is?

Unhandled rejection TypeError: Cannot read property 'data' of undefined
    at /home/pi/pimatic-app/node_modules/pimatic-z-way/z-way.coffee:479:19
    at tryCatcher (/home/pi/pimatic-app/node_modules/pimatic/node_modules/request-promise/node_modules/bluebird/js/main/util.js:26:23)
    at Promise._settlePromiseFromHandler (/home/pi/pimatic-app/node_modules/pimatic/node_modules/request-promise/node_modules/bluebird/js/main/promise.js:510
    at Promise._settlePromiseAt (/home/pi/pimatic-app/node_modules/pimatic/node_modules/request-promise/node_modules/bluebird/js/main/promise.js:584:18)
    at Promise._settlePromises (/home/pi/pimatic-app/node_modules/pimatic/node_modules/request-promise/node_modules/bluebird/js/main/promise.js:700:14)
    at Async._drainQueue (/home/pi/pimatic-app/node_modules/pimatic/node_modules/request-promise/node_modules/bluebird/js/main/async.js:123:16)
    at Async._drainQueues (/home/pi/pimatic-app/node_modules/pimatic/node_modules/request-promise/node_modules/bluebird/js/main/async.js:133:10)
    at Immediate.Async.drainQueues [as _onImmediate] (/home/pi/pimatic-app/node_modules/pimatic/node_modules/request-promise/node_modules/bluebird/js/main/as5:14)
    at processImmediate [as _immediateCallback] (timers.js:383:17)
Unhandled rejection TypeError: Cannot read property 'data' of undefined
    at /home/pi/pimatic-app/node_modules/pimatic-z-way/z-way.coffee:339:19
    at tryCatcher (/home/pi/pimatic-app/node_modules/pimatic/node_modules/request-promise/node_modules/bluebird/js/main/util.js:26:23)
    at Promise._settlePromiseFromHandler (/home/pi/pimatic-app/node_modules/pimatic/node_modules/request-promise/node_modules/bluebird/js/main/promise.js:510
    at Promise._settlePromiseAt (/home/pi/pimatic-app/node_modules/pimatic/node_modules/request-promise/node_modules/bluebird/js/main/promise.js:584:18)
    at Promise._settlePromises (/home/pi/pimatic-app/node_modules/pimatic/node_modules/request-promise/node_modules/bluebird/js/main/promise.js:700:14)
    at Async._drainQueue (/home/pi/pimatic-app/node_modules/pimatic/node_modules/request-promise/node_modules/bluebird/js/main/async.js:123:16)
    at Async._drainQueues (/home/pi/pimatic-app/node_modules/pimatic/node_modules/request-promise/node_modules/bluebird/js/main/async.js:133:10)
    at Immediate.Async.drainQueues [as _onImmediate] (/home/pi/pimatic-app/node_modules/pimatic/node_modules/request-promise/node_modules/bluebird/js/main/as5:14)
    at processImmediate [as _immediateCallback] (timers.js:383:17)

**Comment by ghost** [comment]
i assume that your z-way server is not running. whenever i restart my z-way server i get this messages in pimatic.

**Comment by MMore** [comment]
@DerGrafausB any further information when this happens?

**Comment by DerGrafausB** [comment]
when i stari pimatic in terminal not as a service
