### ISSUE TITLE
Device not found in Log

### ISSUE THREAD

**Issue by BarnyXX** [MMore/pimatic-plugin-template#36]
Hi,

I'm getting this error every 30 seconds and every time one of my Door Contacts is changes its state.

23:35:56.560 [pimatic] debug: Error: device not found
23:35:56.560 [pimatic] debug:>    at DeviceManager.callDeviceActionReq (/home/pi/pimatic-app/node_modules/pimatic/lib/devices.coffee:1632:15)
23:35:56.560 [pimatic] debug:>    at DeviceManager.callDeviceActionReq (/home/pi/pimatic-app/node_modules/pimatic/lib/devices.coffee:10:57)
23:35:56.560 [pimatic] debug:>    at /home/pi/pimatic-app/node_modules/pimatic/node_modules/decl-api/index.js:274:34
23:35:56.560 [pimatic] debug:>    at tryCatcher (/home/pi/pimatic-app/node_modules/pimatic/node_modules/bluebird/js/release/util.js:16:23)
23:35:56.560 [pimatic] debug:>    at Function.Promise.attempt.Promise.try (/home/pi/pimatic-app/node_modules/pimatic/node_modules/bluebird/js/release/method.js:39:29)
23:35:56.560 [pimatic] debug:>    at callActionFromReq (/home/pi/pimatic-app/node_modules/pimatic/node_modules/decl-api/index.js:272:28)
23:35:56.560 [pimatic] debug:>    at /home/pi/pimatic-app/node_modules/pimatic/node_modules/decl-api/index.js:364:16
23:35:56.560 [pimatic] debug:>    at tryCatcher (/home/pi/pimatic-app/node_modules/pimatic/node_modules/bluebird/js/release/util.js:16:23)
23:35:56.560 [pimatic] debug:>    at Function.Promise.attempt.Promise.try (/home/pi/pimatic-app/node_modules/pimatic/node_modules/bluebird/js/release/method.js:39:29)
23:35:56.560 [pimatic] debug:>    at callActionFromReqAndRespond (/home/pi/pimatic-app/node_modules/pimatic/node_modules/decl-api/index.js:362:26)
23:35:56.560 [pimatic] debug:>    at /home/pi/pimatic-app/node_modules/pimatic/node_modules/decl-api/index.js:445:20
23:35:56.560 [pimatic] debug:>    at Layer.handle [as handle_request] (/home/pi/pimatic-app/node_modules/pimatic/node_modules/express/lib/router/layer.js:95:5)
23:35:56.560 [pimatic] debug:>    at next (/home/pi/pimatic-app/node_modules/pimatic/node_modules/express/lib/router/route.js:137:13)
23:35:56.560 [pimatic] debug:>    at Route.dispatch (/home/pi/pimatic-app/node_modules/pimatic/node_modules/express/lib/router/route.js:112:3)
23:35:56.560 [pimatic] debug:>    at Layer.handle [as handle_request] (/home/pi/pimatic-app/node_modules/pimatic/node_modules/express/lib/router/layer.js:95:5)
23:35:56.560 [pimatic] debug:>    at /home/pi/pimatic-app/node_modules/pimatic/node_modules/express/lib/router/index.js:281:22
23:35:56.560 [pimatic] debug:>    at param (/home/pi/pimatic-app/node_modules/pimatic/node_modules/express/lib/router/index.js:354:14)
23:35:56.560 [pimatic] debug:>    at param (/home/pi/pimatic-app/node_modules/pimatic/node_modules/express/lib/router/index.js:365:14)
23:35:56.560 [pimatic] debug:>    at param (/home/pi/pimatic-app/node_modules/pimatic/node_modules/express/lib/router/index.js:365:14)
23:35:56.560 [pimatic] debug:>    at Function.process_params (/home/pi/pimatic-app/node_modules/pimatic/node_modules/express/lib/router/index.js:410:3)
23:35:56.560 [pimatic] debug:>    at next (/home/pi/pimatic-app/node_modules/pimatic/node_modules/express/lib/router/index.js:275:10)
23:35:56.560 [pimatic] debug:>    at next (/home/pi/pimatic-app/node_modules/pimatic/node_modules/express/lib/router/route.js:127:14)
23:35:56.560 [pimatic] debug:>    at /home/pi/pimatic-app/node_modules/pimatic/lib/framework.coffee:992:19
23:35:56.560 [pimatic] debug:>    at Layer.handle [as handle_request] (/home/pi/pimatic-app/node_modules/pimatic/node_modules/express/lib/router/layer.js:95:5)
23:35:56.560 [pimatic] debug:>    at next (/home/pi/pimatic-app/node_modules/pimatic/node_modules/express/lib/router/route.js:137:13)
23:35:56.560 [pimatic] debug:>    at Route.dispatch (/home/pi/pimatic-app/node_modules/pimatic/node_modules/express/lib/router/route.js:112:3)
23:35:56.560 [pimatic] debug:>    at Layer.handle [as handle_request] (/home/pi/pimatic-app/node_modules/pimatic/node_modules/express/lib/router/layer.js:95:5)
23:35:56.560 [pimatic] debug:>    at /home/pi/pimatic-app/node_modules/pimatic/node_modules/express/lib/router/index.js:281:22
23:35:56.560 [pimatic] debug:>    at param (/home/pi/pimatic-app/node_modules/pimatic/node_modules/express/lib/router/index.js:354:14)
23:35:56.560 [pimatic] debug:>    at param (/home/pi/pimatic-app/node_modules/pimatic/node_modules/express/lib/router/index.js:365:14)
23:35:56.560 [pimatic] debug:>    at param (/home/pi/pimatic-app/node_modules/pimatic/node_modules/express/lib/router/index.js:365:14)
23:35:56.560 [pimatic] debug:>    at Function.process_params (/home/pi/pimatic-app/node_modules/pimatic/node_modules/express/lib/router/index.js:410:3)
23:35:56.560 [pimatic] debug:>    at next (/home/pi/pimatic-app/node_modules/pimatic/node_modules/express/lib/router/index.js:275:10)
23:35:56.560 [pimatic] debug:>    at /home/pi/pimatic-app/node_modules/pimatic/lib/framework.coffee:355:11
23:35:56.560 [pimatic] debug:>    at Layer.handle [as handle_request] (/home/pi/pimatic-app/node_modules/pimatic/node_modules/express/lib/router/layer.js:95:5)
23:35:56.560 [pimatic] debug:>    at trim_prefix (/home/pi/pimatic-app/node_modules/pimatic/node_modules/express/lib/router/index.js:317:13)
23:35:56.560 [pimatic] debug:>    at /home/pi/pimatic-app/node_modules/pimatic/node_modules/express/lib/router/index.js:284:7
23:35:56.560 [pimatic] debug:>    at Function.process_params (/home/pi/pimatic-app/node_modules/pimatic/node_modules/express/lib/router/index.js:335:12)
23:35:56.560 [pimatic] debug:>    at next (/home/pi/pimatic-app/node_modules/pimatic/node_modules/express/lib/router/index.js:275:10)
23:35:56.560 [pimatic] debug:>    at _cookieSession (/home/pi/pimatic-app/node_modules/pimatic/node_modules/cookie-session/index.js:126:5)
23:35:56.560 [pimatic] debug:>    at Layer.handle [as handle_request] (/home/pi/pimatic-app/node_modules/pimatic/node_modules/express/lib/router/layer.js:95:5)
23:35:56.560 [pimatic] debug:>    at trim_prefix (/home/pi/pimatic-app/node_modules/pimatic/node_modules/express/lib/router/index.js:317:13)
23:35:56.560 [pimatic] debug:>    at /home/pi/pimatic-app/node_modules/pimatic/node_modules/express/lib/router/index.js:284:7
23:35:56.560 [pimatic] debug:>    at Function.process_params (/home/pi/pimatic-app/node_modules/pimatic/node_modules/express/lib/router/index.js:335:12)
23:35:56.560 [pimatic] debug:>    at next (/home/pi/pimatic-app/node_modules/pimatic/node_modules/express/lib/router/index.js:275:10)
23:35:56.560 [pimatic] debug:>    at jsonParser (/home/pi/pimatic-app/node_modules/pimatic/node_modules/body-parser/lib/types/json.js:109:7)
23:35:56.560 [pimatic] debug:>    at Layer.handle [as handle_request] (/home/pi/pimatic-app/node_modules/pimatic/node_modules/express/lib/router/layer.js:95:5)
23:35:56.560 [pimatic] debug:>    at trim_prefix (/home/pi/pimatic-app/node_modules/pimatic/node_modules/express/lib/router/index.js:317:13)
23:35:56.560 [pimatic] debug:>    at /home/pi/pimatic-app/node_modules/pimatic/node_modules/express/lib/router/index.js:284:7
23:35:56.560 [pimatic] debug:>    at Function.process_params (/home/pi/pimatic-app/node_modules/pimatic/node_modules/express/lib/router/index.js:335:12)
23:35:56.560 [pimatic] debug:>    at next (/home/pi/pimatic-app/node_modules/pimatic/node_modules/express/lib/router/index.js:275:10)
23:35:56.560 [pimatic] debug:>    at urlencodedParser (/home/pi/pimatic-app/node_modules/pimatic/node_modules/body-parser/lib/types/urlencoded.js:91:7)
23:35:56.560 [pimatic] debug:>    at Layer.handle [as handle_request] (/home/pi/pimatic-app/node_modules/pimatic/node_modules/express/lib/router/layer.js:95:5)
23:35:56.560 [pimatic] debug:>    at trim_prefix (/home/pi/pimatic-app/node_modules/pimatic/node_modules/express/lib/router/index.js:317:13)
23:35:56.560 [pimatic] debug:>    at /home/pi/pimatic-app/node_modules/pimatic/node_modules/express/lib/router/index.js:284:7
23:35:56.560 [pimatic] debug:>    at Function.process_params (/home/pi/pimatic-app/node_modules/pimatic/node_modules/express/lib/router/index.js:335:12)
23:35:56.560 [pimatic] debug:>    at next (/home/pi/pimatic-app/node_modules/pimatic/node_modules/express/lib/router/index.js:275:10)
23:35:56.560 [pimatic] debug:>    at cookieParser (/home/pi/pimatic-app/node_modules/pimatic/node_modules/cookie-parser/index.js:56:14)
23:35:56.560 [pimatic] debug:>    at Layer.handle [as handle_request] (/home/pi/pimatic-app/node_modules/pimatic/node_modules/express/lib/router/layer.js:95:5)
23:35:56.560 [pimatic] debug:>    at trim_prefix (/home/pi/pimatic-app/node_modules/pimatic/node_modules/express/lib/router/index.js:317:13)
23:35:56.560 [pimatic] debug:>    at /home/pi/pimatic-app/node_modules/pimatic/node_modules/express/lib/router/index.js:284:7
23:35:56.560 [pimatic] debug:>    at Function.process_params (/home/pi/pimatic-app/node_modules/pimatic/node_modules/express/lib/router/index.js:335:12)
23:35:56.560 [pimatic] debug:>    at next (/home/pi/pimatic-app/node_modules/pimatic/node_modules/express/lib/router/index.js:275:10)
23:35:56.560 [pimatic] debug:>    at /home/pi/pimatic-app/node_modules/pimatic/lib/framework.coffee:264:9
23:35:56.560 [pimatic] debug:>    at Layer.handle [as handle_request] (/home/pi/pimatic-app/node_modules/pimatic/node_modules/express/lib/router/layer.js:95:5)
23:35:56.560 [pimatic] debug:>    at trim_prefix (/home/pi/pimatic-app/node_modules/pimatic/node_modules/express/lib/router/index.js:317:13)
23:35:56.560 [pimatic] debug:>    at /home/pi/pimatic-app/node_modules/pimatic/node_modules/express/lib/router/index.js:284:7
23:35:56.560 [pimatic] debug:>    at Function.process_params (/home/pi/pimatic-app/node_modules/pimatic/node_modules/express/lib/router/index.js:335:12)
23:35:56.560 [pimatic] debug:>    at next (/home/pi/pimatic-app/node_modules/pimatic/node_modules/express/lib/router/index.js:275:10)
23:35:56.560 [pimatic] debug:>    at /home/pi/pimatic-app/node_modules/pimatic/node_modules/connect-timeout/index.js:70:5
23:35:56.560 [pimatic] debug:>    at Layer.handle [as handle_request] (/home/pi/pimatic-app/node_modules/pimatic/node_modules/express/lib/router/layer.js:95:5)
23:35:56.560 [pimatic] debug:>    at trim_prefix (/home/pi/pimatic-app/node_modules/pimatic/node_modules/express/lib/router/index.js:317:13)
23:35:56.560 [pimatic] debug:>    at /home/pi/pimatic-app/node_modules/pimatic/node_modules/express/lib/router/index.js:284:7
23:35:56.560 [pimatic] debug:>    at Function.process_params (/home/pi/pimatic-app/node_modules/pimatic/node_modules/express/lib/router/index.js:335:12)
23:35:56.560 [pimatic] debug:>    at next (/home/pi/pimatic-app/node_modules/pimatic/node_modules/express/lib/router/index.js:275:10)
23:35:56.560 [pimatic] debug:>    at methodOverride (/home/pi/pimatic-app/node_modules/pimatic/node_modules/method-override/index.js:65:14)
23:35:56.560 [pimatic] debug:>    at Layer.handle [as handle_request] (/home/pi/pimatic-app/node_modules/pimatic/node_modules/express/lib/router/layer.js:95:5)
23:35:56.560 [pimatic] debug:>    at trim_prefix (/home/pi/pimatic-app/node_modules/pimatic/node_modules/express/lib/router/index.js:317:13)
23:35:56.560 [pimatic] debug:>    at /home/pi/pimatic-app/node_modules/pimatic/node_modules/express/lib/router/index.js:284:7
23:35:56.560 [pimatic] debug:>    at Function.process_params (/home/pi/pimatic-app/node_modules/pimatic/node_modules/express/lib/router/index.js:335:12)
23:35:56.560 [pimatic] debug:>    at next (/home/pi/pimatic-app/node_modules/pimatic/node_modules/express/lib/router/index.js:275:10)
23:35:56.560 [pimatic] debug:>    at expressInit (/home/pi/pimatic-app/node_modules/pimatic/node_modules/express/lib/middleware/init.js:40:5)
23:35:56.560 [pimatic] debug:>    at Layer.handle [as handle_request] (/home/pi/pimatic-app/node_modules/pimatic/node_modules/express/lib/router/layer.js:95:5)
23:35:56.560 [pimatic] debug:>    at trim_prefix (/home/pi/pimatic-app/node_modules/pimatic/node_modules/express/lib/router/index.js:317:13)
23:35:56.560 [pimatic] debug:>    at /home/pi/pimatic-app/node_modules/pimatic/node_modules/express/lib/router/index.js:284:7
23:35:56.560 [pimatic] debug:>    at Function.process_params (/home/pi/pimatic-app/node_modules/pimatic/node_modules/express/lib/router/index.js:335:12)
23:35:56.560 [pimatic] debug:>    at next (/home/pi/pimatic-app/node_modules/pimatic/node_modules/express/lib/router/index.js:275:10)
23:35:56.560 [pimatic] debug:>    at query (/home/pi/pimatic-app/node_modules/pimatic/node_modules/express/lib/middleware/query.js:44:5)
23:35:56.560 [pimatic] debug:>    at Layer.handle [as handle_request] (/home/pi/pimatic-app/node_modules/pimatic/node_modules/express/lib/router/layer.js:95:5)
23:35:56.560 [pimatic] debug:>    at trim_prefix (/home/pi/pimatic-app/node_modules/pimatic/node_modules/express/lib/router/index.js:317:13)
23:35:56.560 [pimatic] debug:>    at /home/pi/pimatic-app/node_modules/pimatic/node_modules/express/lib/router/index.js:284:7
23:35:56.560 [pimatic] debug:>    at Function.process_params (/home/pi/pimatic-app/node_modules/pimatic/node_modules/express/lib/router/index.js:335:12)
23:35:56.560 [pimatic] debug:>    at next (/home/pi/pimatic-app/node_modules/pimatic/node_modules/express/lib/router/index.js:275:10)
23:35:56.560 [pimatic] debug:>    at Function.handle (/home/pi/pimatic-app/node_modules/pimatic/node_modules/express/lib/router/index.js:174:3)
23:35:56.560 [pimatic] debug:>    at EventEmitter.handle (/home/pi/pimatic-app/node_modules/pimatic/node_modules/express/lib/application.js:174:10)
23:35:56.560 [pimatic] debug:>    at Server.app (/home/pi/pimatic-app/node_modules/pimatic/node_modules/express/lib/express.js:38:9)
23:35:56.560 [pimatic] debug:>    at emitTwo (events.js:87:13)
23:35:56.560 [pimatic] debug:>    at Server.emit (events.js:172:7)
23:35:56.560 [pimatic] debug:>    at HTTPParser.parserOnIncoming [as onIncoming] (_http_server.js:533:12)
23:35:56.560 [pimatic] debug:>    at HTTPParser.parserOnHeadersComplete (_http_common.js:103:23)

Any Suggestions how to fix this?

**Comment by BarnyXX** [comment]
Sorry, I just found it. It was a script which is setting an old DummyContact.
